# Basic
title: asunquan.com
subtitle: 不忘初心 不止于行
welcome_message: 
description: 职场新人 iOS菜鸟 就职于搜狐畅游 从事iOS/tvOS的SDK开发 对于游戏市场有点点了解 平日和一只小Corgi同吃同睡 
creator: <a href="https://github.com/asunquan”>@asunquan</a>

name: asunquan.com
description: 职场新人 iOS菜鸟 就职于搜狐畅游 从事iOS/tvOS的SDK开发 对于游戏市场有点点了解 平日和一只小Corgi同吃同睡 
url: “http://www.asunquan.com”

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: asunquan
    # duoshuo:
# Social
social:
    weibo: asunquan
    github: asunquan    
    mail: asunquan@gmail.com

# Google Analytics
ga:
    id: UA-87028002-1
    host: www.asunquan.com
